// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNdGrWUa6U56vlHRmpTd7cSZvQYfKi3oc',
    appId: '1:204836197660:web:01abcddf39e02eb05196d9',
    messagingSenderId: '204836197660',
    projectId: 'chatbot-3794e',
    authDomain: 'chatbot-3794e.firebaseapp.com',
    storageBucket: 'chatbot-3794e.firebasestorage.app',
    measurementId: 'G-P294MB3FD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoKpW1ecFjBIZxjF6BXzyxFAyeEdlIj-M',
    appId: '1:204836197660:android:f52a79016ccfdece5196d9',
    messagingSenderId: '204836197660',
    projectId: 'chatbot-3794e',
    storageBucket: 'chatbot-3794e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2AEGmS34Nr4eXeb5I6Sn3OVqWFngxvK8',
    appId: '1:204836197660:ios:0b66e84e4ad7a0985196d9',
    messagingSenderId: '204836197660',
    projectId: 'chatbot-3794e',
    storageBucket: 'chatbot-3794e.firebasestorage.app',
    iosBundleId: 'com.chatbot.chatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2AEGmS34Nr4eXeb5I6Sn3OVqWFngxvK8',
    appId: '1:204836197660:ios:0b66e84e4ad7a0985196d9',
    messagingSenderId: '204836197660',
    projectId: 'chatbot-3794e',
    storageBucket: 'chatbot-3794e.firebasestorage.app',
    iosBundleId: 'com.chatbot.chatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNdGrWUa6U56vlHRmpTd7cSZvQYfKi3oc',
    appId: '1:204836197660:web:d1084834a1b95efe5196d9',
    messagingSenderId: '204836197660',
    projectId: 'chatbot-3794e',
    authDomain: 'chatbot-3794e.firebaseapp.com',
    storageBucket: 'chatbot-3794e.firebasestorage.app',
    measurementId: 'G-KYNL2S857E',
  );
}
